spring:
  application:
    name: ProjectFlow-API
  datasource:
    url: jdbc:postgresql://localhost:5432/projectflow_api
    username: postgres
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  error:
    include-stacktrace: never
api:
  security:
    token:
      secret: ${JWT_Secret:123456}
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG